CREATE USER "vip" IDENTIFIED BY "1"  
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "vip" QUOTA UNLIMITED ON "SYSTEM";

-- ROLES
--alter session set "_ORACLE_SCRIPT"=true; 
-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "vip" ;
GRANT CREATE TABLE TO "vip" ;